### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)
# this is a one dimenisonal array

[1 2 3]


In [2]:
a.shape

(3,)

In [3]:
a.ndim

1

In [4]:
# create a another one dimensional array with 10 elements
b=np.array([1,2,3,4,5,6,7,8,9])

In [5]:
b.shape

(9,)

In [6]:
b.ndim

1

In [7]:
c = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(c.shape)
print(c.ndim)

(10,)
1


In [8]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape

(2, 3)

In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr.ndim)
print(arr.shape)

3
(2, 2, 3)


In [11]:
five_comma_five_2d = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(five_comma_five_2d.shape)
print(five_comma_five_2d.ndim)

(5, 5)
2


In [12]:
# create a 2d array with shape 3*3
np.array([[1,2,3],[1,2,3],[1,2,3]]).ndim

2

In [13]:
# create a another 2d array of shape 4*4
np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [14]:
#create a another 2d array of 2*3
np.array([[1,2,3],[1,2,3]]).ndim

2

In [15]:
#create a 3d array with shape 2*2*2
np.array([[[1,2],[1,2]],[[1,2],[1,2]]]).ndim


3

In [16]:
# create a 3d array with 3*3*3 shape
np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]).ndim

3

# Note
2 means 1d

2*2 means 2d

2*2*2 means 3d

2*2*2*2 means 4d array

In [17]:
# create a array with a shape 3*3*3
np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]]).shape

(3, 2, 3)

In [18]:
# create a array with a shape 2*2*2
np.array([[[0, 0],[1, 1]],[[2, 2],[3, 3]]]).shape

(2, 2, 2)

In [19]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [20]:
# create with a dtype a int
# dtype
np.array([1,2,3],dtype=int)

array([1, 2, 3])

In [21]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [22]:
# create a array using a arrange
np.arange(0, 101, 5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [23]:
x = 5          # integer scalar
y = 3.14       # float scalar
z = True       # boolean scalar


In [24]:
# with reshape
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [26]:
# your task create a 45 elements array and then reshape it
# with reshape
np.arange(45).reshape(3,3,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [27]:
# make a own question and do it
# Q: Create a 4x4 array of numbers 1 to 16 and find the sum of each row and each column
own_arr = np.arange(1, 17).reshape(4, 4)
print("Array:\n", own_arr)
print("Row-wise sum:", np.sum(own_arr, axis=1))
print("Column-wise sum:", np.sum(own_arr, axis=0))

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


In [28]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
# np.random
np.random.random((3,4))

array([[0.62357407, 0.88824116, 0.86918545, 0.80461674],
       [0.22396918, 0.29999214, 0.47862766, 0.62844439],
       [0.96984377, 0.08858311, 0.47028436, 0.89422913]])

In [31]:
# np.linspace
np.linspace(-10,10,dtype=int)

array([-10, -10, -10,  -9,  -9,  -8,  -8,  -8,  -7,  -7,  -6,  -6,  -6,
        -5,  -5,  -4,  -4,  -4,  -3,  -3,  -2,  -2,  -2,  -1,  -1,   0,
         0,   1,   1,   1,   2,   2,   3,   3,   3,   4,   4,   5,   5,
         5,   6,   6,   7,   7,   7,   8,   8,   9,   9,  10])

In [32]:
# np.linspace
np.linspace(-5,5,10,dtype=int)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  5])

In [33]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [34]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
# ndim
a3.ndim

3

In [36]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [38]:
# itemsize
a3.itemsize

8

In [39]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [40]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [41]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [44]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

### Array Functions

In [45]:
a1 = np.random.random((3,3))
a1

array([[0.92544505, 0.33194887, 0.25432742],
       [0.01201428, 0.96069485, 0.08435757],
       [0.7455223 , 0.47834813, 0.39502991]])

In [46]:
a1 = np.round(a1*100)
a1

array([[93., 33., 25.],
       [ 1., 96.,  8.],
       [75., 48., 40.]])

In [47]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([  6975., 152064.,   8000.])

In [48]:
np.max(a1)

np.float64(96.0)

In [49]:
np.min(a2)

np.int64(12)

In [50]:
# mean/median/std/var
np.var(a1)

np.float64(1074.0246913580247)

In [51]:
# trigonomoetric functions
np.sin(a1)

array([[-0.94828214,  0.99991186, -0.13235175],
       [ 0.84147098,  0.98358775,  0.98935825],
       [-0.38778164, -0.76825466,  0.74511316]])

In [52]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [53]:
# log and exponents
np.exp(a1)

array([[2.45124554e+40, 2.14643580e+14, 7.20048993e+10],
       [2.71828183e+00, 4.92345829e+41, 2.98095799e+03],
       [3.73324200e+32, 7.01673591e+20, 2.35385267e+17]])

### np.ceil() → Ceiling

Definition: Rounds each number UP to the nearest integer.

Always goes toward +∞, no matter what.

In [54]:
import numpy as np

arr = np.array([1.2, 2.7, -1.5, -2.3])
arr


array([ 1.2,  2.7, -1.5, -2.3])

In [55]:
np.ceil(arr)

array([ 2.,  3., -1., -2.])

### np.floor() → Floor

Definition: Rounds each number DOWN to the nearest integer.

Always goes toward -∞.

In [56]:
np.floor(arr)


array([ 1.,  2., -2., -3.])

### np.round() → Round (to nearest)

Definition: Rounds each number to the nearest integer.

If decimal = 0.5 → rounds to nearest even integer (NumPy behavior).

In [57]:
np.round(arr)


array([ 1.,  3., -2., -2.])

### Indexing and Slicing

In [58]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [59]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
a2[1,0]

np.int64(4)

In [62]:
a2[1,2]

np.int64(6)

In [63]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
a3[1,0,1]

np.int64(5)

In [65]:
a3[0,1,0]

np.int64(2)

In [66]:
### find the elements 7
a3[1,1,1]

np.int64(7)

In [67]:
# find elements 3
a3[0,1,1]

np.int64(3)

In [68]:
# whats the output
a3[1,1,0]

np.int64(6)

In [69]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Iterating

In [70]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [71]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [73]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [74]:
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


### Reshaping

In [75]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Stacking

In [76]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [79]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [80]:
from PIL import Image
import numpy as np

# Load image
img = Image.open("images.jpg")  # your image file

# Convert to NumPy array
img_array = np.array(img)

![My Image](images.jpg)

In [81]:
img_array

array([[[ 55, 127,  87],
        [ 57, 121,  87],
        [ 65, 112,  96],
        ...,
        [ 80,  89,  24],
        [ 86, 129,  40],
        [193, 249, 222]],

       [[142, 185, 158],
        [ 19,  63,  36],
        [ 12,  62,  33],
        ...,
        [198, 206, 155],
        [170, 196, 123],
        [  3,  39,   0]],

       [[101,  82,  86],
        [122, 130, 115],
        [ 92, 152, 100],
        ...,
        [176, 181, 158],
        [130, 123,  81],
        [239, 228, 146]],

       ...,

       [[127, 148, 193],
        [ 39,  63,  87],
        [ 81, 112,  96],
        ...,
        [248, 174, 199],
        [140,  90, 115],
        [ 52, 103,  47]],

       [[ 31,  37,  97],
        [167, 176, 217],
        [ 68,  86,  90],
        ...,
        [145,  89, 114],
        [116,  81, 114],
        [142, 181, 160]],

       [[169, 129, 182],
        [ 39,   7,  57],
        [229, 211, 255],
        ...,
        [137, 117, 142],
        [172, 188, 221],
        [  6,  62,  87]]

In [82]:
img_array.shape

(501, 399, 3)

In [83]:
img_array.ndim

3